# Generated by Django 3.1.5 on 2021-04-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chackout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chackout',
            new_name='Chack',
        ),
    ]
