# Generated by Django 3.1 on 2021-04-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210419_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PLACED', 'PLACED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default='Pending', max_length=50),
        ),
    ]
